# Generated by Django 3.2.3 on 2022-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20220303_1327'),
        ('crm', 'customer_account'),
    ]

    operations = [
    ]
